import { Product } from "@/components/ui/ProductCard";

export const products: Product[] = [
  {
    id: 1,
    name: "Hydrolat de Camomille Pure",
    nameAr: "مقطر البابونج النقي",
    category: "Visage",
    categoryAr: "الوجه",
    price: 155,
    image: "/images/hydrolat-camomille.jpg",
    rating: 5,
    reviews: 44,
    badge: "Best-seller",
    badgeAr: "الأكثر مبيعاً",
    description:
      "Hydrolat de camomille 100 % pur — apaise les rougeurs, hydrate et illumine les peaux sensibles.",
    descriptionAr: "مقطر البابونج النقي 100% — يهدئ الاحمرار، يرطب ويضيء البشرة الحساسة.",
  },
  {
    id: 3,
    name: "Tabrima – Essence des Herbes Marocaines",
    nameAr: "تبريمة للحمام المغربي",
    category: "Bain & Hammam",
    categoryAr: "الحمام المغربي",
    price: 110,
    image: "/images/tabrima-hammam.jpg",
    rating: 5,
    reviews: 45,
    badge: "Exclusif",
    badgeAr: "حصري",
    description:
      "Mélange aromatique de plantes pour hammam — purifie le corps, parfume la vapeur et ravive les rituels ancestraux.",
    descriptionAr: "مزيج عطري من النباتات للحمام — ينقي الجسم، يعطر البخار ويحيي الطقوس القديمة.",
  },
  {
    id: 13,
    name: "Tabrima – Formule Intense",
    nameAr: "تبريمة – تركيبة مكثفة",
    category: "Bain & Hammam",
    categoryAr: "الحمام المغربي",
    price: 120,
    image: "/images/tabrima-hammam2.jpg",
    rating: 5,
    reviews: 31,
    badge: "Nouveau",
    badgeAr: "جديد",
    description:
      "Version concentrée de la tabrima — pour un hammam encore plus purifiants et aromatique.",
    descriptionAr: "نسخة مركزة من التبريمة — لحمام أكثر تنقية وعطرًا.",
  },
  {
    id: 4,
    name: "Savon Beldi Marocain",
    nameAr: "صابون بلدي مغربي",
    category: "Bain & Hammam",
    categoryAr: "الحمام المغربي",
    price: 95,
    image: "/images/savon-beldi.jpg",
    rating: 5,
    reviews: 88,
    badge: "Best-seller",
    badgeAr: "الأكثر مبيعاً",
    description:
      "Savon noir marocain authentique — exfolie, purifie en profondeur et laisse la peau incroyablement douce.",
    descriptionAr: "صابون أسود مغربي أصيل — يقشر وينقف بعمق ويترك البشرة ناعمة بشكل لا يصدق.",
  },
  {
    id: 7,
    name: "Beurre Corporel Tropical Mango",
    nameAr: "زبدة الجسم بالمانجو الاستوائية",
    category: "Corps",
    categoryAr: "الجسم",
    price: 155,
    image: "/images/tropical-mango-butter.jpg",
    rating: 5,
    reviews: 52,
    badge: "Nouveau",
    badgeAr: "جديد",
    description:
      "Beurre nourrissant à la mangue tropicale — fond sur la peau pour une hydratation longue durée.",
    descriptionAr: "زبدة مغذية بالمانجو الاستوائية — تذوب على البشرة لترطيب يدوم طويلاً.",
  },
  {
    id: 14,
    name: "Coco Shea Nourish – Beurre Corps",
    nameAr: "كوكو شيا نوريش – زبدة الجسم",
    category: "Corps",
    categoryAr: "الجسم",
    price: 150,
    image: "/images/cocoshea-nourish.jpg",
    rating: 5,
    reviews: 43,
    badge: "Nouveau",
    badgeAr: "جديد",
    description:
      "Beurre corps enrichi à la noix de coco et au karité — nourrit et apaise les peaux sèches durablement.",
    descriptionAr: "زبدة جسم غنية بجوز الهند والشيا — تغذي وتهدئ البشرة الجافة بشكل دائم.",
  },
  {
    id: 9,
    name: "Gommage Éclat Curcuma & Citron",
    nameAr: "مقشر الجسم بالكركم والليمون",
    category: "Corps",
    categoryAr: "الجسم",
    price: 130,
    image: "/images/body-scrub-tumeric-lemon.jpg",
    rating: 4,
    reviews: 28,
    description:
      "Exfoliant détoxifiant au curcuma et citron — éclaircit, dépigmente et illumine la peau.",
    descriptionAr: "مقشر مزيل للسموم بالكركم والليمون — يفتح، يعالج التصبغات ويضيء البشرة.",
  },
  {
    id: 10,
    name: "Gommage Apaisant Nila & Lavande",
    nameAr: "مقشر الجسم بالنيلة واللافندر",
    category: "Corps",
    categoryAr: "الجسم",
    price: 130,
    image: "/images/body-scrub-nila-lavender.jpg",
    rating: 5,
    reviews: 34,
    description:
      "Exfoliant cicatrisant au nila marocain et à la lavande — apaise et unifie la peau sensible.",
    descriptionAr: "مقشر معالج بالنيلة المغربية واللافندر — يهدئ ويوحد البشرة الحساسة.",
  },
  {
    id: 11,
    name: "Gommage Douceur Coco & Rose",
    nameAr: "مقشر الجسم بجوز الهند والورد",
    category: "Corps",
    categoryAr: "الجسم",
    price: 130,
    image: "/images/body-scrub-coconut-rose.jpg",
    rating: 5,
    reviews: 57,
    badge: "Nouveau",
    badgeAr: "جديد",
    description:
      "Gommage régénérant à la noix de coco et aux pétales de rose — peau veloutée et parfumée.",
    descriptionAr: "مقشر مجدد بجوز الهند وبتلات الورد — بشرة مخملية ومعطرة.",
  },
  {
    id: 15,
    name: "Sel de Bain Lavande & Camomille",
    nameAr: "ملح الاستحمام اللافندر والبابونج",
    category: "Mains & Pieds",
    categoryAr: "اليدين والقدمين",
    price: 85,
    image: "/images/bath-salt-lavender-chamomile.jpg",
    rating: 5,
    reviews: 22,
    badge: "Nouveau",
    badgeAr: "جديد",
    description:
      "Sel de bain apaisant à la lavande et à la camomille — détend les muscles, relaxe l'esprit.",
    descriptionAr: "ملح استحمام مهدئ باللافندر والبابونج — يريح العضلات ويهدئ العقل.",
  },
  {
    id: 16,
    name: "Sel de Bain Citrus & Orange",
    nameAr: "ملح الاستحمام الحمضيات والبرتقال",
    category: "Mains & Pieds",
    categoryAr: "اليدين والقدمين",
    price: 85,
    image: "/images/bath-salt-citrus-orange.jpg",
    rating: 5,
    reviews: 18,
    badge: "Nouveau",
    badgeAr: "جديد",
    description:
      "Sel de bain énergisant aux agrumes et à l'orange — revitalise le corps et éveille les sens.",
    descriptionAr: "ملح استحمام منشط بالحمضيات والبرتقال — يجدد نشاط الجسم ويوقظ الحواس.",
  },
  {
    id: 17,
    name: "Sel de Bain Hibiscus & Rose",
    nameAr: "ملح الاستحمام الكركديه والورد",
    category: "Mains & Pieds",
    categoryAr: "اليدين والقدمين",
    price: 85,
    image: "/images/bath-salt-hibiscus-rose.jpg",
    rating: 5,
    reviews: 15,
    badge: "Nouveau",
    badgeAr: "جديد",
    description:
      "Sel de bain floral à l'hibiscus et à la rose — adoucit la peau et offre un moment de pure romance.",
    descriptionAr: "ملح استحمام زهري بالكركديه والورد — يلين البشرة ويمنح لحظة من الرومانسية الخالصة.",
  },
  {
    id: 18,
    name: "Sel de Bain Menthe & Eucalyptus",
    nameAr: "ملح الاستحمام النعناع والإيكاليبتوس",
    category: "Mains & Pieds",
    categoryAr: "اليدين والقدمين",
    price: 85,
    image: "/images/bath-salt-peppermint-eucalyptus.jpg",
    rating: 5,
    reviews: 19,
    badge: "Nouveau",
    badgeAr: "جديد",
    description:
      "Sel de bain fraîcheur à la menthe et à l'eucalyptus — purifie, revitalise et libère les voies respiratoires.",
    descriptionAr: "ملح استحمام منعش بالنعناع والإيكاليبتوس — ينقي وينشط ويفتح مجاري التنفس.",
  },
  {
    id: 19,
    name: "La Coloration Soin – Teinte Naturelle",
    nameAr: "الصبغة العلاجية – اللون الطبيعي",
    category: "Cheveux",
    categoryAr: "الشعر",
    price: 120,
    image: "/images/coloration-soin-1.jpg",
    rating: 5,
    reviews: 36,
    badge: "Best-seller",
    badgeAr: "الأكثر مبيعاً",
    description:
      "Coloration traitante 100 % naturelle — colore tout en nourrissant et fortifiant le cheveu en profondeur.",
    descriptionAr: "صبغة علاجية طبيعية 100% — تلوّن مع تغذية الشعر وتقويته بعمق.",
  },
  {
    id: 20,
    name: "La Coloration Soin – Teinte Intense",
    nameAr: "الصبغة العلاجية – اللون المكثف",
    category: "Cheveux",
    categoryAr: "الشعر",
    price: 120,
    image: "/images/coloration-soin-2.jpg",
    rating: 5,
    reviews: 29,
    badge: "Nouveau",
    badgeAr: "جديد",
    description:
      "Coloration traitante à pigmentation intense — pour un résultat couleur éclatant et longue tenue.",
    descriptionAr: "صبغة علاجية بتلوين مكثف — لنتيجة لون مشرق وطويل الأمد.",
  },
  {
    id: 21,
    name: "La Coloration Soin – Teinte Dorée",
    nameAr: "الصبغة العلاجية – اللون الذهبي",
    category: "Cheveux",
    categoryAr: "الشعر",
    price: 120,
    image: "/images/coloration-soin-3.jpg",
    rating: 5,
    reviews: 24,
    badge: "Nouveau",
    badgeAr: "جديد",
    description:
      "Coloration traitante aux reflets dorés — sublime les cheveux tout en les fortifiant.",
    descriptionAr: "صبغة علاجية بانعكاسات ذهبية — تجمّل الشعر مع تقويته.",
  },
  {
    id: 22,
    name: "Secret Intima – Mousse Nettoyante Intime",
    nameAr: "سيكريت إنتيما – رغوة التنظيف الحميم",
    category: "Soins intimes",
    categoryAr: "العناية الحميمة",
    price: 100,
    image: "/images/secret-intima.jpg",
    rating: 5,
    reviews: 47,
    badge: "Best-seller",
    badgeAr: "الأكثر مبيعاً",
    description:
      "Mousse nettoyante intime douce et naturelle — respecte le pH naturel, protège et assainit délicatement.",
    descriptionAr: "رغوة تنظيف حميمة ناعمة وطبيعية — تحترم الرقم الهيدروجيني الطبيعي وتحمي وتطهر برفق.",
  },
  {
    id: 23,
    name: "Bougie Parfumée Bella Secret",
    nameAr: "شمعة بيلا سيكريت العطرية",
    category: "Ambiance & Senteurs",
    categoryAr: "الأجواء والعطور",
    price: 130,
    image: "/images/bougie.jpg",
    rating: 5,
    reviews: 33,
    badge: "Nouveau",
    badgeAr: "جديد",
    description:
      "Bougie parfumée artisanale — embaume votre intérieur d'un parfum délicat et envoûtant.",
    descriptionAr: "شمعة عطرية يدوية الصنع — تملأ منزلك بعطر لطيف وساحر.",
  },
];

// Review images are screenshots of real client reviews
export const testimonials = [
  { id: 1 }, { id: 2 }, { id: 3 }, { id: 4 },
  { id: 5 }, { id: 6 }, { id: 7 }, { id: 8 },
];

export const blogPosts = [
  {
    id: 1,
    title: "Les bienfaits des microalgues pour la peau",
    titleAr: "فوائد الطحالب الدقيقة للبشرة",
    excerpt:
      "Découvrez pourquoi les microalgues sont le super-ingrédient de la cosmétique naturelle et comment elles transforment la peau.",
    excerptAr:
      "اكتشفي لماذا تعتبر الطحالب الدقيقة المكون الخارق في مستحضرات التجميل الطبيعية وكيف تحول البشرة.",
    category: "Science & Beauté",
    categoryAr: "العلم والجمال",
    date: "12 Mars 2025",
    dateAr: "12 مارس 2025",
    readTime: "5 min",
    readTimeAr: "5 دقائق",
    image: "/images/algue.jpeg",
    slug: "bienfaits-microalgues-peau",
    content: "Les microalgues, véritables trésors marins, sont de plus en plus prisées en cosmétique naturelle pour leurs propriétés exceptionnelles. Riches en antioxydants, en vitamines et en minéraux, elles aident à lutter contre le vieillissement cutané en neutralisant les radicaux libres. De plus, leur capacité unique à retenir l'eau offre une hydratation intense et durable aux peaux les plus assoiffées. \n\nEn intégrant les microalgues dans votre routine beauté, vous favorisez le renouvellement cellulaire et redonnez de l'éclat à votre teint. Ces organismes microscopiques possèdent également des vertus apaisantes, idéales pour calmer les rougeurs et les irritations. Opter pour des soins à base de microalgues, c'est choisir l'efficacité de la nature pour une peau saine, lumineuse et revitalisée jour après jour.",
    contentAr: "تعتبر الطحالب الدقيقة، وهي كنوز بحرية حقيقية، ذات شعبية متزايدة في مستحضرات التجميل الطبيعية لخصائصها الاستثنائية. غنية بمضادات الأكسدة والفيتامينات والمعادن، فهي تساعد في مكافحة شيخوخة الجلد عن طريق تحييد الجذور الحرة. بالإضافة إلى ذلك، فإن قدرتها الفريدة على الاحتفاظ بالماء توفر ترطيبًا مكثفًا ودائمًا لأكثر أنواع البشرة عطشًا. \n\nمن خلال دمج الطحالب الدقيقة في روتين جمالك، يمكنك تعزيز تجديد الخلايا واستعادة إشراق بشرتك. تمتلك هذه الكائنات المجهرية أيضًا خصائص مهدئة، مثالية لتهدئة الاحمرار والتهيج. إن اختيار العناية بالبشرة التي تعتمد على الطحالب الدقيقة يعني اختيار فعالية الطبيعة للحصول على بشرة صحية ومشرقة ومنتعشة يومًا بعد يوم."
  },
  {
    id: 2,
    title: "Le rituel hammam marocain : guide complet",
    titleAr: "طقوس الحمام المغربي: دليل شامل",
    excerpt:
      "Explorez les secrets du bain marocain traditionnel et reproduisez cette expérience luxueuse chez vous.",
    excerptAr:
      "اكتشفي أسرار الحمام المغربي التقليدي وأعيدي إنشاء هذه التجربة الفاخرة في منزلك.",
    category: "Rituels Beauté",
    categoryAr: "طقوس الجمال",
    date: "5 Mars 2025",
    dateAr: "5 مارس 2025",
    readTime: "7 min",
    readTimeAr: "7 دقائق",
    image: "/images/hamam.jpeg",
    slug: "rituel-hammam-marocain-guide",
    content: "Le hammam marocain n'est pas seulement un bain, c'est un véritable rituel de purification pour le corps et l'esprit. Cette tradition millénaire repose sur des étapes précises pour nettoyer la peau en profondeur et relâcher les tensions musculaires. L'expérience commence par un bain de vapeur qui ouvre les pores, préparant ainsi la peau à recevoir les soins. \n\nEnsuite vient l'application du savon noir, un produit naturel à base d'olives broyées, suivi d'un gommage vigoureux avec un gant kessa pour éliminer les cellules mortes. Le rituel se termine souvent par un masque purifiant au ghassoul et une hydratation riche à l'huile d'argan. Reproduire ce rituel chez soi permet de s'accorder un moment de détente absolue tout en profitant des bienfaits ancestraux de la beauté marocaine.",
    contentAr: "الحمام المغربي ليس مجرد حمام، بل هو طقس تنقية حقيقي للجسد والروح. يعتمد هذا التقليد الممتد لألف عام على خطوات دقيقة لتنظيف البشرة بعمق وتخفيف توتر العضلات. تبدأ التجربة بحمام بخار يفتح المسام، ويجهز البشرة لتلقي العلاجات. \n\nثم يأتي تطبيق الصابون الأسود، وهو منتج طبيعي يعتمد على الزيتون المطحون، يليه فرك قوي بقفاز الكيسة لإزالة الخلايا الميتة. غالبًا ما تنتهي الطقوس بقناع منقي مع الغاسول وترطيب غني بزيت الأركان. يتيح لك إعادة إنتاج هذه الطقوس في المنزل أن تمنح نفسك لحظة من الاسترخاء المطلق مع الاستمتاع بفوائد الجمال المغربي القديم."
  },
  {
    id: 3,
    title: "Routine cheveux naturelle pour cet été",
    titleAr: "روتين الشعر الطبيعي لهذا الصيف",
    excerpt:
      "Nos meilleures astuces prouvées pour protéger et nourrir vos cheveux de manière 100 % naturelle.",
    excerptAr:
      "أفضل نصائحنا المجربة لحماية وتغذية شعرك بطريقة طبيعية 100%.",
    category: "Cheveux",
    categoryAr: "الشعر",
    date: "28 Février 2025",
    dateAr: "28 فبراير 2025",
    readTime: "6 min",
    readTimeAr: "6 دقائق",
    image: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&h=400&fit=crop",
    slug: "routine-cheveux-naturelle-ete",
  },
];
